done

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,20 +1,26 @@
 #!/usr/bin/env bash
-# A script that that transfers a file from our client to a server
+# This script transfers a file from a client to a server using scp.
 
+# Check if all required parameters are provided
 if [ "$#" -ne 4 ]; then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-FILE_PATH="$1"
-SERVER_IP="$2"
+# Assign parameters to variables
+PATH_TO_FILE="$1"
+IP="$2"
 USERNAME="$3"
-SSH_KEY_PATH="$4"
+PATH_TO_SSH_KEY="$4"
 
-scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
+# Use scp to transfer the file to the server's home directory (~)
+# Disable strict host key checking with "-o StrictHostKeyChecking=no"
+scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"
 
+# Check if the scp command was successful
 if [ "$?" -eq 0 ]; then
-    echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
+  echo "File transfer successful."
 else
-    echo "File transfer failed."
+  echo "File transfer failed."
+  exit 1
 fi
